/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAMMCallee,
  IAMMCalleeInterface,
} from "../../../contracts/interfaces/IAMMCallee";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "ammCall",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAMMCallee__factory {
  static readonly abi = _abi;
  static createInterface(): IAMMCalleeInterface {
    return new Interface(_abi) as IAMMCalleeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAMMCallee {
    return new Contract(address, _abi, runner) as unknown as IAMMCallee;
  }
}
